### ISSUE TITLE
うんこをどうするか

### ISSUE THREAD

**Issue by sKawashima** [YngLab/GitPractice#1]
消したい

**Comment by ShumpeiKano** [comment]
消さない

**Comment by sKawashima** [comment]
ああああああああああああ

**Comment by ShumpeiKano** [comment]
吊らない

**Comment by Yakan-Kettle** [comment]
消せない過去

**Comment by sKawashima** [comment]
流石にどうかと思う

**Comment by Yakan-Kettle** [comment]
"貴様は殺す"　は許された・・・？

**Comment by sKawashima** [comment]
もう全部消そう（）

**Comment by k-odashi** [comment]
ああぴゃああああああ

**Comment by sKawashima** [comment]
真面目な話、GitHubについてわからんことあったらこのリポジトリにissue追加して聞いてください「

**Comment by Yakan-Kettle** [comment]
$B%a%"%I$+$iD>@\JV?.$7$?$i$I$&$J$k$+$N%F%9%H(B

**Comment by Yakan-Kettle** [comment]
↑のは「メアドから直接返信したらどうなるかのテスト」と書いて、登録メールアドレスから、GitHubを介さずそのまま返信したものです。メッセージそのものは届きはするものの、文字化けするし、（メールアドレス側の）スレッドにも載らないようです。

**Comment by sKawashima** [comment]
消すのは諦めました
